import building2 from '../../assets/building2.jpeg';

export const ProjectList = [
    {
      id: 1,
      image: building2,
      address: '544 Carroll Street',
      market: 'Gowanus, Brooklyn',
      units: 133,
      phase: 'Pre-Construction',
      design_phase: '175,000 SF GFA',
      design_phase_completion: '75',
      last_issuance: 'ASI #1',
      start_date: {type: 'Start Date', time: new Date(2023, 4, 1)},
      proj_end_date: {type: 'Projected End Date', time: new Date(2024, 2, 14)},
      budget: 1572640,
      gmp: 'TBD',
      status: 'planning',
      sched_var: 'flex',
      notes: 'test 1'
    },
    {
      id: 2,
      image: building2,
      address: '653 Union Street',
      market: 'Gowanus, Brooklyn',
      units: 133,
      phase: 'Construction',
      design_phase: '175,000 SF GFA',
      design_phase_completion: '35',
      last_issuance: 'ASI #1',
      start_date: {type: 'Start Date', time: new Date(2023, 4, 1)},
      proj_end_date: {type: 'Projected End Date', time: new Date(2024, 2, 14)},
      budget: 2336580,
      gmp: 'TBD',
      status: 'build',
      sched_var: 'set',
      notes: 'test 2'
    },
    {
      id: 3,
      image: building2,
      address: '544 Carroll Street',
      market: 'Gowanus, Brooklyn',
      units: 133,
      phase: 'Pre-Construction',
      design_phase: '175,000 SF GFA',
      design_phase_completion: '85',
      last_issuance: 'ASI #1',
      start_date: {type: 'Start Date', time: new Date(2023, 4, 1)},
      proj_end_date: {type: 'Projected End Date', time: new Date(2024, 2, 14)},
      budget: 1572640,
      gmp: 'TBD',
      status: 'planning',
      sched_var: 'flex',
      notes: 'test 1'
    },
    {
      id: 4,
      image: building2,
      address: '653 Union Street',
      market: 'Gowanus, Brooklyn',
      units: 133,
      phase: 'Construction',
      design_phase: '175,000 SF GFA',
      design_phase_completion: '25',
      last_issuance: 'ASI #1',
      start_date: {type: 'Start Date', time: new Date(2023, 4, 1)},
      proj_end_date: {type: 'Projected End Date', time: new Date(2024, 2, 14)},
      budget: 2336580,
      gmp: 'TBD',
      status: 'build',
      sched_var: 'set',
      notes: 'test 2'
    }
  ];
